# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160304_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='binarythreshold',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='edgedetection',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='greyscale',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='histogram',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='resize',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='smoothen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
