# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160304_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='binarythreshold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='edgedetection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='greyscale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='histogram',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='resize',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='smoothen',
            field=models.BooleanField(default=False),
        ),
    ]
