# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160304_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='legolas',
            field=models.BooleanField(default=False),
        ),
    ]
