# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_document_legolas'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='legolas_parameter',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
