# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_document_legolas_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='legolas_parameter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
