# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160710_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='foregroundextract',
        ),
        migrations.RemoveField(
            model_name='document',
            name='resize',
        ),
    ]
