# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160710_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='threshold',
            field=models.BooleanField(default=False),
        ),
    ]
