# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_document_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='threshold',
        ),
    ]
