# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_document_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dilate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='erode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='gaussianBlur',
            field=models.BooleanField(default=False),
        ),
    ]
