# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_document_medianblur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='dilate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='erode',
        ),
        migrations.RemoveField(
            model_name='document',
            name='medianBlur',
        ),
    ]
