# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20160710_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
