# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20160710_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='legolas',
        ),
        migrations.RemoveField(
            model_name='document',
            name='legolas_parameter',
        ),
    ]
