# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20160710_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='docfile',
            new_name='image_file',
        ),
    ]
