# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_document_dilate_kernel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='binarythreshold',
            new_name='binary_threshold',
        ),
    ]
