# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_document_smoothen_kernel_array'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='dilate_kernel',
            new_name='dilate_ksize',
        ),
    ]
