# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20160712_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='edgedetection',
            new_name='canny',
        ),
    ]
