# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20160712_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='thresh',
            new_name='binary_threshold_threshold',
        ),
        migrations.AddField(
            model_name='document',
            name='canny_threshold',
            field=models.CharField(blank=True, default=(100, 200), max_length=100, null=True),
        ),
    ]
