# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20160712_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sobel_ksize',
            field=models.IntegerField(default=5, max_length=16),
        ),
    ]
