# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_document_sobel_ksize'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gaussian_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='gaussian_sigmaX',
            field=models.IntegerField(default=1.5, max_length=16),
        ),
    ]
