# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20160712_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='gaussian_sigmaX',
            field=models.FloatField(default=1.5, max_length=16),
        ),
    ]
