# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_document_median_blur_ksize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='gaussian_sigmaX',
            field=models.FloatField(default=1.5),
        ),
    ]
