# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_auto_20160713_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='binary_threshold_threshold',
            field=models.IntegerField(default=157),
        ),
        migrations.AlterField(
            model_name='document',
            name='median_blur_ksize',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='document',
            name='sobel_ksize',
            field=models.IntegerField(default=5),
        ),
    ]
