# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20160713_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='erode_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
    ]
