# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_document_erode_ksize'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='closed_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='opend_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
    ]
