# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_document_average_blur'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='average_blur_ksize',
            field=models.IntegerField(default=5),
        ),
    ]
