# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_document_average_blur_ksize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='average_blur_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
    ]
