# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_auto_20160713_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='gaussian_ksize',
            field=models.CharField(blank=True, default=(31, 31), max_length=100, null=True),
        ),
    ]
