# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_auto_20160713_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='sobelfilter',
            new_name='close_binary',
        ),
        migrations.AddField(
            model_name='document',
            name='closed_binary_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='dilate_binary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='dilate_binary_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='erode_binary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='erode_binary_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='hist_equalize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='open_binary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='opend_binary_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rotation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='rotation_degree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='scale_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='scale_area_ratio',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='scale_linear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='scale_linear_ratio',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='shift_coords',
            field=models.CharField(blank=True, default=(0, 0), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='sobel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='binary_threshold_threshold',
            field=models.IntegerField(default=128),
        ),
    ]
